//user
export const LOADING_SUCCESS = 'LOADING_SUCCESS'
export const LOADING_FAILED = 'LOADING_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
// export const SUCCESS_ALERT = 'SUCCESS_ALERT'
// export const ERROR_ALERT = 'ERROR_ALERT'
export const LOGOUT = 'LOGOUT'
export const SET_JOINED = 'SET_JOINED'

export const CLEAR_REGISTRATION_ALERT = 'CLEAR_REGISTRATION_ALERT'
export const CLEAR_LOGIN_ALERT = 'CLEAR_LOGIN_ALERT'

//blocker
export const SET_BLOCKER = 'SET_BLOCKER'
export const REMOVE_BLOCKER = 'REMOVE_BLOCKER'

//popup
export const SHOW_POPUP = 'SHOW_POPUP'
export const HIDE_POPUP = 'HIDE_POPUP'
