//user
export const LOADING_SUCCESS = 'LOADING_SUCCESS'
export const LOADING_FAILED = 'LOADING_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const LOGOUT = 'LOGOUT'
export const CLEAR_REGISTRATION_ALERT = 'CLEAR_REGISTRATION_ALERT'
export const CLEAR_LOGIN_ALERT = 'CLEAR_LOGIN_ALERT'

//collection
export const SET_COLLECTION = 'SET_COLLECTION'
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'

//blocker
export const SET_CLICKED_BLOCKER = 'SET_BLOCKER'
export const REMOVE_BLOCKER = 'REMOVE_BLOCKER'
export const SET_UNCLICKED_BLOCKER = 'SET_UNCLICKED_BLOCKER'

//createCollection
export const SHOW_CREATE_COLLECTION = 'SHOW_CREATE_COLLECTION'
export const HIDE_CREATE_COLLECTION = 'HIDE_CREATE_COLLECTION'
export const SET_TOPIC = 'SET_TOPIC'
export const SET_TITLE_AND_DESCRIPTION = 'SET_TITLE_AND_DESCRIPTION'
export const SET_FILE = 'SET_FILE'
export const CLEAR_TOPIC = 'CLEAR_TOPIC'
export const CREATE_COLLECTION_RESPONSE = 'CREATE_COLLECTION_RESPONSE'
export const CLEAR_COLLECTION_RESPONSE = 'CLEAR_COLLECTION_RESPONSE'
export const TOGGLE_UPDATE_TRIGGER = 'TOGGLE_UPDATE_TRIGGER'

//popup
export const SHOW_POPUP = 'SHOW_POPUP'
export const HIDE_POPUP = 'HIDE_POPUP'
